
const Data = [
  {
    id: "1",
    title: "Bacon Burger",
    category: "Burger",
    price: "$20",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/2-1.png",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast ",
  },
  {
    id: "2",
    title: "Cheese Butter",
    category: "Burger",
    price: "$15",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/7-1.png",
    desc: " A quintessential South Indian Breakfast! Made with protein-packed urad dal ",
  },
  {
    id: "3",
    title: "Chicken Burger",
    category: "Burger",
    price: "$12",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/8-1.png",
    desc: "A staple across Indian households, moong dal is widely used in a number ",
  },
  {
    id: "4",
    title: "Blueberry Shake",
    category: "Cold Drink",
    price: "$15",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/5-1.png",
    desc: "A classic dish that never goes out of style. The quintessential chana kulcha ",
  },
  {
    id: "5",
    title: "Fresh Lime",
    category: "Cold Drink",
    price: "$17",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/16-1.png",
    desc: "Lime are a versatile food that can be cooked for any meal of the day.",
  },
  {
    id: "6",
    title: "Iced Tea Bottle",
    category: "Cold Drink",
    price: "$10",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/25-1.png",
    desc: "Don't get intimidated by the list of ingredients for any meal of the day.",
  },
  {
    id: "7",
    title: "Black Coffee",
    category: "Hot Drink",
    price: "$9",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/4-1.png",
    desc: "Get your daily dose of perfect protein. Pieces of surmai any meal of the day,",
  },
  {
    id: "8",
    title: "Hot Cappuccino",
    category: "Hot Drink",
    price: "$8",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/21-1.png",
    desc: "Your family will thank you for this fantastic bowl of dum aloo cooked. ",
  },
  {
    id: "9",
    title: "Iced Coffee",
    category: "Hot Drink",
    price: "$5",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/23-1.png",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with  ",
  },
  {
    id: "10",
    title: "Apricot Chicken",
    category: "Pizza",
    price: "$20",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/1-1.png",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with .",
  },
  {
    id: "11",
    title: "Chicken Hawaii",
    category: "Pizza",
    price: "$20",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/9-1.png",
    desc: "A rich gravy made of khus khus, coconut and milk that ",
  },
  {
    id: "12",
    title: "Grand Italiano",
    category: "Pizza",
    price: "$20",
    img: "https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/17-1.png",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with",
  },
  
];

export default Data;
